### ISSUE TITLE
Media query example

### ISSUE THREAD

**Issue by keligijus** [ausrabickute/Interior_Design#1]
https://github.com/ausrabickute/Interior_Design/blob/c7b317a6e9098aa74e6bf57201f7a7da242a9c96/style.css#L81-L87

```css
 .title1 { 
   display: grid; 
   grid-gap: 20px; 
   padding-top: 30px; 
   padding-bottom: 75px; 

  @media screen and (min-width: 640px) {
    grid-template-columns: repeat(3, 1fr); 
  }
} 
```
